// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sandbox/v1/sandbox.proto

package sandboxpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceKind int32

const (
	ResourceKind_RESOURCE_KIND_UNSPECIFIED ResourceKind = 0
	ResourceKind_RESOURCE_KIND_SANDBOX     ResourceKind = 1
	ResourceKind_RESOURCE_KIND_TEMPLATE    ResourceKind = 2
	ResourceKind_RESOURCE_KIND_CLAIM       ResourceKind = 3
	ResourceKind_RESOURCE_KIND_WARM_POOL   ResourceKind = 4
)

// Enum value maps for ResourceKind.
var (
	ResourceKind_name = map[int32]string{
		0: "RESOURCE_KIND_UNSPECIFIED",
		1: "RESOURCE_KIND_SANDBOX",
		2: "RESOURCE_KIND_TEMPLATE",
		3: "RESOURCE_KIND_CLAIM",
		4: "RESOURCE_KIND_WARM_POOL",
	}
	ResourceKind_value = map[string]int32{
		"RESOURCE_KIND_UNSPECIFIED": 0,
		"RESOURCE_KIND_SANDBOX":     1,
		"RESOURCE_KIND_TEMPLATE":    2,
		"RESOURCE_KIND_CLAIM":       3,
		"RESOURCE_KIND_WARM_POOL":   4,
	}
)

func (x ResourceKind) Enum() *ResourceKind {
	p := new(ResourceKind)
	*p = x
	return p
}

func (x ResourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[0].Descriptor()
}

func (ResourceKind) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[0]
}

func (x ResourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceKind.Descriptor instead.
func (ResourceKind) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

type ShutdownPolicy int32

const (
	ShutdownPolicy_SHUTDOWN_POLICY_UNSPECIFIED       ShutdownPolicy = 0
	ShutdownPolicy_SHUTDOWN_POLICY_RETAIN            ShutdownPolicy = 1
	ShutdownPolicy_SHUTDOWN_POLICY_DELETE            ShutdownPolicy = 2
	ShutdownPolicy_SHUTDOWN_POLICY_DELETE_FOREGROUND ShutdownPolicy = 3
)

// Enum value maps for ShutdownPolicy.
var (
	ShutdownPolicy_name = map[int32]string{
		0: "SHUTDOWN_POLICY_UNSPECIFIED",
		1: "SHUTDOWN_POLICY_RETAIN",
		2: "SHUTDOWN_POLICY_DELETE",
		3: "SHUTDOWN_POLICY_DELETE_FOREGROUND",
	}
	ShutdownPolicy_value = map[string]int32{
		"SHUTDOWN_POLICY_UNSPECIFIED":       0,
		"SHUTDOWN_POLICY_RETAIN":            1,
		"SHUTDOWN_POLICY_DELETE":            2,
		"SHUTDOWN_POLICY_DELETE_FOREGROUND": 3,
	}
)

func (x ShutdownPolicy) Enum() *ShutdownPolicy {
	p := new(ShutdownPolicy)
	*p = x
	return p
}

func (x ShutdownPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShutdownPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[1].Descriptor()
}

func (ShutdownPolicy) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[1]
}

func (x ShutdownPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShutdownPolicy.Descriptor instead.
func (ShutdownPolicy) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

type NetworkPolicyManagement int32

const (
	NetworkPolicyManagement_NETWORK_POLICY_MANAGEMENT_UNSPECIFIED NetworkPolicyManagement = 0
	NetworkPolicyManagement_NETWORK_POLICY_MANAGEMENT_MANAGED     NetworkPolicyManagement = 1
	NetworkPolicyManagement_NETWORK_POLICY_MANAGEMENT_UNMANAGED   NetworkPolicyManagement = 2
)

// Enum value maps for NetworkPolicyManagement.
var (
	NetworkPolicyManagement_name = map[int32]string{
		0: "NETWORK_POLICY_MANAGEMENT_UNSPECIFIED",
		1: "NETWORK_POLICY_MANAGEMENT_MANAGED",
		2: "NETWORK_POLICY_MANAGEMENT_UNMANAGED",
	}
	NetworkPolicyManagement_value = map[string]int32{
		"NETWORK_POLICY_MANAGEMENT_UNSPECIFIED": 0,
		"NETWORK_POLICY_MANAGEMENT_MANAGED":     1,
		"NETWORK_POLICY_MANAGEMENT_UNMANAGED":   2,
	}
)

func (x NetworkPolicyManagement) Enum() *NetworkPolicyManagement {
	p := new(NetworkPolicyManagement)
	*p = x
	return p
}

func (x NetworkPolicyManagement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicyManagement) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[2].Descriptor()
}

func (NetworkPolicyManagement) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[2]
}

func (x NetworkPolicyManagement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicyManagement.Descriptor instead.
func (NetworkPolicyManagement) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

type EnvVarsInjectionPolicy int32

const (
	EnvVarsInjectionPolicy_ENV_VARS_INJECTION_POLICY_UNSPECIFIED EnvVarsInjectionPolicy = 0
	EnvVarsInjectionPolicy_ENV_VARS_INJECTION_POLICY_ALLOWED     EnvVarsInjectionPolicy = 1
	EnvVarsInjectionPolicy_ENV_VARS_INJECTION_POLICY_OVERRIDES   EnvVarsInjectionPolicy = 2
	EnvVarsInjectionPolicy_ENV_VARS_INJECTION_POLICY_DISALLOWED  EnvVarsInjectionPolicy = 3
)

// Enum value maps for EnvVarsInjectionPolicy.
var (
	EnvVarsInjectionPolicy_name = map[int32]string{
		0: "ENV_VARS_INJECTION_POLICY_UNSPECIFIED",
		1: "ENV_VARS_INJECTION_POLICY_ALLOWED",
		2: "ENV_VARS_INJECTION_POLICY_OVERRIDES",
		3: "ENV_VARS_INJECTION_POLICY_DISALLOWED",
	}
	EnvVarsInjectionPolicy_value = map[string]int32{
		"ENV_VARS_INJECTION_POLICY_UNSPECIFIED": 0,
		"ENV_VARS_INJECTION_POLICY_ALLOWED":     1,
		"ENV_VARS_INJECTION_POLICY_OVERRIDES":   2,
		"ENV_VARS_INJECTION_POLICY_DISALLOWED":  3,
	}
)

func (x EnvVarsInjectionPolicy) Enum() *EnvVarsInjectionPolicy {
	p := new(EnvVarsInjectionPolicy)
	*p = x
	return p
}

func (x EnvVarsInjectionPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvVarsInjectionPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[3].Descriptor()
}

func (EnvVarsInjectionPolicy) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[3]
}

func (x EnvVarsInjectionPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvVarsInjectionPolicy.Descriptor instead.
func (EnvVarsInjectionPolicy) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

type WarmPoolUpdateStrategy int32

const (
	WarmPoolUpdateStrategy_WARM_POOL_UPDATE_STRATEGY_UNSPECIFIED  WarmPoolUpdateStrategy = 0
	WarmPoolUpdateStrategy_WARM_POOL_UPDATE_STRATEGY_ON_REPLENISH WarmPoolUpdateStrategy = 1
	WarmPoolUpdateStrategy_WARM_POOL_UPDATE_STRATEGY_RECREATE     WarmPoolUpdateStrategy = 2
)

// Enum value maps for WarmPoolUpdateStrategy.
var (
	WarmPoolUpdateStrategy_name = map[int32]string{
		0: "WARM_POOL_UPDATE_STRATEGY_UNSPECIFIED",
		1: "WARM_POOL_UPDATE_STRATEGY_ON_REPLENISH",
		2: "WARM_POOL_UPDATE_STRATEGY_RECREATE",
	}
	WarmPoolUpdateStrategy_value = map[string]int32{
		"WARM_POOL_UPDATE_STRATEGY_UNSPECIFIED":  0,
		"WARM_POOL_UPDATE_STRATEGY_ON_REPLENISH": 1,
		"WARM_POOL_UPDATE_STRATEGY_RECREATE":     2,
	}
)

func (x WarmPoolUpdateStrategy) Enum() *WarmPoolUpdateStrategy {
	p := new(WarmPoolUpdateStrategy)
	*p = x
	return p
}

func (x WarmPoolUpdateStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarmPoolUpdateStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[4].Descriptor()
}

func (WarmPoolUpdateStrategy) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[4]
}

func (x WarmPoolUpdateStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarmPoolUpdateStrategy.Descriptor instead.
func (WarmPoolUpdateStrategy) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvVar) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type ContainerPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContainerPort int32                  `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPort) Reset() {
	*x = ContainerPort{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPort) ProtoMessage() {}

func (x *ContainerPort) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPort.ProtoReflect.Descriptor instead.
func (*ContainerPort) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerPort) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ContainerPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           []*EnvVar              `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	Ports         []*ContainerPort       `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Container) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Container) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Container) GetPorts() []*ContainerPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type PodTemplate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Labels             map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations        map[string]string      `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Containers         []*Container           `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	ServiceAccountName string                 `protobuf:"bytes,4,opt,name=service_account_name,json=serviceAccountName,proto3" json:"service_account_name,omitempty"`
	RuntimeClassName   string                 `protobuf:"bytes,5,opt,name=runtime_class_name,json=runtimeClassName,proto3" json:"runtime_class_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PodTemplate) Reset() {
	*x = PodTemplate{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodTemplate) ProtoMessage() {}

func (x *PodTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodTemplate.ProtoReflect.Descriptor instead.
func (*PodTemplate) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *PodTemplate) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PodTemplate) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PodTemplate) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *PodTemplate) GetServiceAccountName() string {
	if x != nil {
		return x.ServiceAccountName
	}
	return ""
}

func (x *PodTemplate) GetRuntimeClassName() string {
	if x != nil {
		return x.RuntimeClassName
	}
	return ""
}

type SandboxResource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PodTemplate    *PodTemplate           `protobuf:"bytes,2,opt,name=pod_template,json=podTemplate,proto3" json:"pod_template,omitempty"`
	Replicas       int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	ShutdownTime   string                 `protobuf:"bytes,4,opt,name=shutdown_time,json=shutdownTime,proto3" json:"shutdown_time,omitempty"`
	ShutdownPolicy ShutdownPolicy         `protobuf:"varint,5,opt,name=shutdown_policy,json=shutdownPolicy,proto3,enum=sandbox.v1.ShutdownPolicy" json:"shutdown_policy,omitempty"`
	Service        string                 `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	ServiceFqdn    string                 `protobuf:"bytes,7,opt,name=service_fqdn,json=serviceFqdn,proto3" json:"service_fqdn,omitempty"`
	PodIps         []string               `protobuf:"bytes,8,rep,name=pod_ips,json=podIps,proto3" json:"pod_ips,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxResource) Reset() {
	*x = SandboxResource{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxResource) ProtoMessage() {}

func (x *SandboxResource) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxResource.ProtoReflect.Descriptor instead.
func (*SandboxResource) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxResource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SandboxResource) GetPodTemplate() *PodTemplate {
	if x != nil {
		return x.PodTemplate
	}
	return nil
}

func (x *SandboxResource) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *SandboxResource) GetShutdownTime() string {
	if x != nil {
		return x.ShutdownTime
	}
	return ""
}

func (x *SandboxResource) GetShutdownPolicy() ShutdownPolicy {
	if x != nil {
		return x.ShutdownPolicy
	}
	return ShutdownPolicy_SHUTDOWN_POLICY_UNSPECIFIED
}

func (x *SandboxResource) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SandboxResource) GetServiceFqdn() string {
	if x != nil {
		return x.ServiceFqdn
	}
	return ""
}

func (x *SandboxResource) GetPodIps() []string {
	if x != nil {
		return x.PodIps
	}
	return nil
}

type SandboxTemplateResource struct {
	state                   protoimpl.MessageState  `protogen:"open.v1"`
	Metadata                *Metadata               `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PodTemplate             *PodTemplate            `protobuf:"bytes,2,opt,name=pod_template,json=podTemplate,proto3" json:"pod_template,omitempty"`
	NetworkPolicyManagement NetworkPolicyManagement `protobuf:"varint,3,opt,name=network_policy_management,json=networkPolicyManagement,proto3,enum=sandbox.v1.NetworkPolicyManagement" json:"network_policy_management,omitempty"`
	EnvVarsInjectionPolicy  EnvVarsInjectionPolicy  `protobuf:"varint,4,opt,name=env_vars_injection_policy,json=envVarsInjectionPolicy,proto3,enum=sandbox.v1.EnvVarsInjectionPolicy" json:"env_vars_injection_policy,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SandboxTemplateResource) Reset() {
	*x = SandboxTemplateResource{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxTemplateResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxTemplateResource) ProtoMessage() {}

func (x *SandboxTemplateResource) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxTemplateResource.ProtoReflect.Descriptor instead.
func (*SandboxTemplateResource) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxTemplateResource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SandboxTemplateResource) GetPodTemplate() *PodTemplate {
	if x != nil {
		return x.PodTemplate
	}
	return nil
}

func (x *SandboxTemplateResource) GetNetworkPolicyManagement() NetworkPolicyManagement {
	if x != nil {
		return x.NetworkPolicyManagement
	}
	return NetworkPolicyManagement_NETWORK_POLICY_MANAGEMENT_UNSPECIFIED
}

func (x *SandboxTemplateResource) GetEnvVarsInjectionPolicy() EnvVarsInjectionPolicy {
	if x != nil {
		return x.EnvVarsInjectionPolicy
	}
	return EnvVarsInjectionPolicy_ENV_VARS_INJECTION_POLICY_UNSPECIFIED
}

type SandboxClaimResource struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Metadata                *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TemplateName            string                 `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	WarmPoolName            string                 `protobuf:"bytes,3,opt,name=warm_pool_name,json=warmPoolName,proto3" json:"warm_pool_name,omitempty"`
	Env                     []*EnvVar              `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	ShutdownTime            string                 `protobuf:"bytes,5,opt,name=shutdown_time,json=shutdownTime,proto3" json:"shutdown_time,omitempty"`
	TtlSecondsAfterFinished int32                  `protobuf:"varint,6,opt,name=ttl_seconds_after_finished,json=ttlSecondsAfterFinished,proto3" json:"ttl_seconds_after_finished,omitempty"`
	ShutdownPolicy          ShutdownPolicy         `protobuf:"varint,7,opt,name=shutdown_policy,json=shutdownPolicy,proto3,enum=sandbox.v1.ShutdownPolicy" json:"shutdown_policy,omitempty"`
	SandboxName             string                 `protobuf:"bytes,8,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	PodIps                  []string               `protobuf:"bytes,9,rep,name=pod_ips,json=podIps,proto3" json:"pod_ips,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SandboxClaimResource) Reset() {
	*x = SandboxClaimResource{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxClaimResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxClaimResource) ProtoMessage() {}

func (x *SandboxClaimResource) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxClaimResource.ProtoReflect.Descriptor instead.
func (*SandboxClaimResource) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *SandboxClaimResource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SandboxClaimResource) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SandboxClaimResource) GetWarmPoolName() string {
	if x != nil {
		return x.WarmPoolName
	}
	return ""
}

func (x *SandboxClaimResource) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SandboxClaimResource) GetShutdownTime() string {
	if x != nil {
		return x.ShutdownTime
	}
	return ""
}

func (x *SandboxClaimResource) GetTtlSecondsAfterFinished() int32 {
	if x != nil {
		return x.TtlSecondsAfterFinished
	}
	return 0
}

func (x *SandboxClaimResource) GetShutdownPolicy() ShutdownPolicy {
	if x != nil {
		return x.ShutdownPolicy
	}
	return ShutdownPolicy_SHUTDOWN_POLICY_UNSPECIFIED
}

func (x *SandboxClaimResource) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *SandboxClaimResource) GetPodIps() []string {
	if x != nil {
		return x.PodIps
	}
	return nil
}

type SandboxWarmPoolResource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TemplateName   string                 `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Replicas       int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	UpdateStrategy WarmPoolUpdateStrategy `protobuf:"varint,4,opt,name=update_strategy,json=updateStrategy,proto3,enum=sandbox.v1.WarmPoolUpdateStrategy" json:"update_strategy,omitempty"`
	ReadyReplicas  int32                  `protobuf:"varint,5,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxWarmPoolResource) Reset() {
	*x = SandboxWarmPoolResource{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxWarmPoolResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxWarmPoolResource) ProtoMessage() {}

func (x *SandboxWarmPoolResource) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxWarmPoolResource.ProtoReflect.Descriptor instead.
func (*SandboxWarmPoolResource) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *SandboxWarmPoolResource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SandboxWarmPoolResource) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SandboxWarmPoolResource) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *SandboxWarmPoolResource) GetUpdateStrategy() WarmPoolUpdateStrategy {
	if x != nil {
		return x.UpdateStrategy
	}
	return WarmPoolUpdateStrategy_WARM_POOL_UPDATE_STRATEGY_UNSPECIFIED
}

func (x *SandboxWarmPoolResource) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

type ManagedResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  ResourceKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=sandbox.v1.ResourceKind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Resource:
	//
	//	*ManagedResource_Sandbox
	//	*ManagedResource_Template
	//	*ManagedResource_Claim
	//	*ManagedResource_WarmPool
	Resource      isManagedResource_Resource `protobuf_oneof:"resource"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedResource) Reset() {
	*x = ManagedResource{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedResource) ProtoMessage() {}

func (x *ManagedResource) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedResource.ProtoReflect.Descriptor instead.
func (*ManagedResource) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *ManagedResource) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNSPECIFIED
}

func (x *ManagedResource) GetResource() isManagedResource_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ManagedResource) GetSandbox() *SandboxResource {
	if x != nil {
		if x, ok := x.Resource.(*ManagedResource_Sandbox); ok {
			return x.Sandbox
		}
	}
	return nil
}

func (x *ManagedResource) GetTemplate() *SandboxTemplateResource {
	if x != nil {
		if x, ok := x.Resource.(*ManagedResource_Template); ok {
			return x.Template
		}
	}
	return nil
}

func (x *ManagedResource) GetClaim() *SandboxClaimResource {
	if x != nil {
		if x, ok := x.Resource.(*ManagedResource_Claim); ok {
			return x.Claim
		}
	}
	return nil
}

func (x *ManagedResource) GetWarmPool() *SandboxWarmPoolResource {
	if x != nil {
		if x, ok := x.Resource.(*ManagedResource_WarmPool); ok {
			return x.WarmPool
		}
	}
	return nil
}

type isManagedResource_Resource interface {
	isManagedResource_Resource()
}

type ManagedResource_Sandbox struct {
	Sandbox *SandboxResource `protobuf:"bytes,2,opt,name=sandbox,proto3,oneof"`
}

type ManagedResource_Template struct {
	Template *SandboxTemplateResource `protobuf:"bytes,3,opt,name=template,proto3,oneof"`
}

type ManagedResource_Claim struct {
	Claim *SandboxClaimResource `protobuf:"bytes,4,opt,name=claim,proto3,oneof"`
}

type ManagedResource_WarmPool struct {
	WarmPool *SandboxWarmPoolResource `protobuf:"bytes,5,opt,name=warm_pool,json=warmPool,proto3,oneof"`
}

func (*ManagedResource_Sandbox) isManagedResource_Resource() {}

func (*ManagedResource_Template) isManagedResource_Resource() {}

func (*ManagedResource_Claim) isManagedResource_Resource() {}

func (*ManagedResource_WarmPool) isManagedResource_Resource() {}

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ManagedResource       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *CreateResourceRequest) GetResource() *ManagedResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ResourceKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=sandbox.v1.ResourceKind" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *GetResourceRequest) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNSPECIFIED
}

func (x *GetResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ResourceKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=sandbox.v1.ResourceKind" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *ListResourcesRequest) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNSPECIFIED
}

func (x *ListResourcesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type UpdateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ManagedResource       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResourceRequest) GetResource() *ManagedResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ResourceKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=sandbox.v1.ResourceKind" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteResourceRequest) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNSPECIFIED
}

func (x *DeleteResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ManagedResource       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *ResourceResponse) GetResource() *ManagedResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ManagedResource     `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *ListResourcesResponse) GetResources() []*ManagedResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_sandbox_v1_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x18sandbox/v1/sandbox.proto\x12\n" +
	"sandbox.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a$gnostic/openapi/v3/annotations.proto\"\xd2\x02\n" +
	"\bMetadata\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x04name\x12(\n" +
	"\tnamespace\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\tnamespace\x128\n" +
	"\x06labels\x18\x03 \x03(\v2 .sandbox.v1.Metadata.LabelsEntryR\x06labels\x12G\n" +
	"\vannotations\x18\x04 \x03(\v2%.sandbox.v1.Metadata.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x06EnvVar\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\"s\n" +
	"\rContainerPort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x0econtainer_port\x18\x02 \x01(\x05B\v\xfaB\b\x1a\x06\x18\xff\xff\x03(\x01R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xcc\x01\n" +
	"\tContainer\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1d\n" +
	"\x05image\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12$\n" +
	"\x03env\x18\x05 \x03(\v2\x12.sandbox.v1.EnvVarR\x03env\x12/\n" +
	"\x05ports\x18\x06 \x03(\v2\x19.sandbox.v1.ContainerPortR\x05ports\"\xb2\x03\n" +
	"\vPodTemplate\x12;\n" +
	"\x06labels\x18\x01 \x03(\v2#.sandbox.v1.PodTemplate.LabelsEntryR\x06labels\x12J\n" +
	"\vannotations\x18\x02 \x03(\v2(.sandbox.v1.PodTemplate.AnnotationsEntryR\vannotations\x12?\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\x15.sandbox.v1.ContainerB\b\xfaB\x05\x92\x01\x02\b\x01R\n" +
	"containers\x120\n" +
	"\x14service_account_name\x18\x04 \x01(\tR\x12serviceAccountName\x12,\n" +
	"\x12runtime_class_name\x18\x05 \x01(\tR\x10runtimeClassName\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x02\n" +
	"\x0fSandboxResource\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.sandbox.v1.MetadataB\x03\xe0A\x02R\bmetadata\x12?\n" +
	"\fpod_template\x18\x02 \x01(\v2\x17.sandbox.v1.PodTemplateB\x03\xe0A\x02R\vpodTemplate\x12%\n" +
	"\breplicas\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x01(\x00R\breplicas\x12#\n" +
	"\rshutdown_time\x18\x04 \x01(\tR\fshutdownTime\x12C\n" +
	"\x0fshutdown_policy\x18\x05 \x01(\x0e2\x1a.sandbox.v1.ShutdownPolicyR\x0eshutdownPolicy\x12\x18\n" +
	"\aservice\x18\x06 \x01(\tR\aservice\x12!\n" +
	"\fservice_fqdn\x18\a \x01(\tR\vserviceFqdn\x12\x17\n" +
	"\apod_ips\x18\b \x03(\tR\x06podIps\"\xd1\x02\n" +
	"\x17SandboxTemplateResource\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.sandbox.v1.MetadataB\x03\xe0A\x02R\bmetadata\x12?\n" +
	"\fpod_template\x18\x02 \x01(\v2\x17.sandbox.v1.PodTemplateB\x03\xe0A\x02R\vpodTemplate\x12_\n" +
	"\x19network_policy_management\x18\x03 \x01(\x0e2#.sandbox.v1.NetworkPolicyManagementR\x17networkPolicyManagement\x12]\n" +
	"\x19env_vars_injection_policy\x18\x04 \x01(\x0e2\".sandbox.v1.EnvVarsInjectionPolicyR\x16envVarsInjectionPolicy\"\xb6\x03\n" +
	"\x14SandboxClaimResource\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.sandbox.v1.MetadataB\x03\xe0A\x02R\bmetadata\x12/\n" +
	"\rtemplate_name\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\ftemplateName\x12$\n" +
	"\x0ewarm_pool_name\x18\x03 \x01(\tR\fwarmPoolName\x12$\n" +
	"\x03env\x18\x04 \x03(\v2\x12.sandbox.v1.EnvVarR\x03env\x12#\n" +
	"\rshutdown_time\x18\x05 \x01(\tR\fshutdownTime\x12D\n" +
	"\x1attl_seconds_after_finished\x18\x06 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x17ttlSecondsAfterFinished\x12C\n" +
	"\x0fshutdown_policy\x18\a \x01(\x0e2\x1a.sandbox.v1.ShutdownPolicyR\x0eshutdownPolicy\x12!\n" +
	"\fsandbox_name\x18\b \x01(\tR\vsandboxName\x12\x17\n" +
	"\apod_ips\x18\t \x03(\tR\x06podIps\"\x9a\x02\n" +
	"\x17SandboxWarmPoolResource\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.sandbox.v1.MetadataB\x03\xe0A\x02R\bmetadata\x12/\n" +
	"\rtemplate_name\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\ftemplateName\x12#\n" +
	"\breplicas\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\breplicas\x12K\n" +
	"\x0fupdate_strategy\x18\x04 \x01(\x0e2\".sandbox.v1.WarmPoolUpdateStrategyR\x0eupdateStrategy\x12%\n" +
	"\x0eready_replicas\x18\x05 \x01(\x05R\rreadyReplicas\"\xca\x02\n" +
	"\x0fManagedResource\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.sandbox.v1.ResourceKindB\x03\xe0A\x02R\x04kind\x127\n" +
	"\asandbox\x18\x02 \x01(\v2\x1b.sandbox.v1.SandboxResourceH\x00R\asandbox\x12A\n" +
	"\btemplate\x18\x03 \x01(\v2#.sandbox.v1.SandboxTemplateResourceH\x00R\btemplate\x128\n" +
	"\x05claim\x18\x04 \x01(\v2 .sandbox.v1.SandboxClaimResourceH\x00R\x05claim\x12B\n" +
	"\twarm_pool\x18\x05 \x01(\v2#.sandbox.v1.SandboxWarmPoolResourceH\x00R\bwarmPoolB\n" +
	"\n" +
	"\bresource\"U\n" +
	"\x15CreateResourceRequest\x12<\n" +
	"\bresource\x18\x01 \x01(\v2\x1b.sandbox.v1.ManagedResourceB\x03\xe0A\x02R\bresource\"\x91\x01\n" +
	"\x12GetResourceRequest\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.sandbox.v1.ResourceKindB\x03\xe0A\x02R\x04kind\x12(\n" +
	"\tnamespace\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\tnamespace\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x04name\"s\n" +
	"\x14ListResourcesRequest\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.sandbox.v1.ResourceKindB\x03\xe0A\x02R\x04kind\x12(\n" +
	"\tnamespace\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\tnamespace\"U\n" +
	"\x15UpdateResourceRequest\x12<\n" +
	"\bresource\x18\x01 \x01(\v2\x1b.sandbox.v1.ManagedResourceB\x03\xe0A\x02R\bresource\"\x94\x01\n" +
	"\x15DeleteResourceRequest\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.sandbox.v1.ResourceKindB\x03\xe0A\x02R\x04kind\x12(\n" +
	"\tnamespace\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\tnamespace\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x04name\"K\n" +
	"\x10ResourceResponse\x127\n" +
	"\bresource\x18\x01 \x01(\v2\x1b.sandbox.v1.ManagedResourceR\bresource\"R\n" +
	"\x15ListResourcesResponse\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.sandbox.v1.ManagedResourceR\tresources*\x9a\x01\n" +
	"\fResourceKind\x12\x1d\n" +
	"\x19RESOURCE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESOURCE_KIND_SANDBOX\x10\x01\x12\x1a\n" +
	"\x16RESOURCE_KIND_TEMPLATE\x10\x02\x12\x17\n" +
	"\x13RESOURCE_KIND_CLAIM\x10\x03\x12\x1b\n" +
	"\x17RESOURCE_KIND_WARM_POOL\x10\x04*\x90\x01\n" +
	"\x0eShutdownPolicy\x12\x1f\n" +
	"\x1bSHUTDOWN_POLICY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SHUTDOWN_POLICY_RETAIN\x10\x01\x12\x1a\n" +
	"\x16SHUTDOWN_POLICY_DELETE\x10\x02\x12%\n" +
	"!SHUTDOWN_POLICY_DELETE_FOREGROUND\x10\x03*\x94\x01\n" +
	"\x17NetworkPolicyManagement\x12)\n" +
	"%NETWORK_POLICY_MANAGEMENT_UNSPECIFIED\x10\x00\x12%\n" +
	"!NETWORK_POLICY_MANAGEMENT_MANAGED\x10\x01\x12'\n" +
	"#NETWORK_POLICY_MANAGEMENT_UNMANAGED\x10\x02*\xbd\x01\n" +
	"\x16EnvVarsInjectionPolicy\x12)\n" +
	"%ENV_VARS_INJECTION_POLICY_UNSPECIFIED\x10\x00\x12%\n" +
	"!ENV_VARS_INJECTION_POLICY_ALLOWED\x10\x01\x12'\n" +
	"#ENV_VARS_INJECTION_POLICY_OVERRIDES\x10\x02\x12(\n" +
	"$ENV_VARS_INJECTION_POLICY_DISALLOWED\x10\x03*\x97\x01\n" +
	"\x16WarmPoolUpdateStrategy\x12)\n" +
	"%WARM_POOL_UPDATE_STRATEGY_UNSPECIFIED\x10\x00\x12*\n" +
	"&WARM_POOL_UPDATE_STRATEGY_ON_REPLENISH\x10\x01\x12&\n" +
	"\"WARM_POOL_UPDATE_STRATEGY_RECREATE\x10\x022\x8c\b\n" +
	"\x0eSandboxService\x12\xb7\x01\n" +
	"\x0eCreateResource\x12!.sandbox.v1.CreateResourceRequest\x1a\x1c.sandbox.v1.ResourceResponse\"d\xbaGI\n" +
	"\bresource\x12\x17Create sandbox resource\x1a$Create Sandbox or extension resource\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/resources\x12\xdf\x01\n" +
	"\vGetResource\x12\x1e.sandbox.v1.GetResourceRequest\x1a\x1c.sandbox.v1.ResourceResponse\"\x91\x01\xbaG_\n" +
	"\bresource\x12\x14Get sandbox resource\x1a=Get Sandbox or extension resource by kind, namespace and name\x82\xd3\xe4\x93\x02)\x12'/v1/resources/{kind}/{namespace}/{name}\x12\xd8\x01\n" +
	"\rListResources\x12 .sandbox.v1.ListResourcesRequest\x1a!.sandbox.v1.ListResourcesResponse\"\x81\x01\xbaGV\n" +
	"\bresource\x12\x16List sandbox resources\x1a2List Sandbox or extension resources in a namespace\x82\xd3\xe4\x93\x02\"\x12 /v1/resources/{kind}/{namespace}\x12\xb7\x01\n" +
	"\x0eUpdateResource\x12!.sandbox.v1.UpdateResourceRequest\x1a\x1c.sandbox.v1.ResourceResponse\"d\xbaGI\n" +
	"\bresource\x12\x17Update sandbox resource\x1a$Update Sandbox or extension resource\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/resources\x12\xc8\x01\n" +
	"\x0eDeleteResource\x12!.sandbox.v1.DeleteResourceRequest\x1a\x16.google.protobuf.Empty\"{\xbaGI\n" +
	"\bresource\x12\x17Delete sandbox resource\x1a$Delete Sandbox or extension resource\x82\xd3\xe4\x93\x02)*'/v1/resources/{kind}/{namespace}/{name}B\xe0\x01\xbaG\xa0\x01\x12V\n" +
	"\vsandbox-api\x12B管理 Agent Sandbox Pod，提供控制面 API，操作 K8s 资源2\x031.0\x1a$\n" +
	"\x15http://localhost:8080\x12\vHost Server* :\x1e\n" +
	"\x1c\n" +
	"\tBasicAuth\x12\x0f\n" +
	"\r\n" +
	"\x04http*\x05basicZ:github.com/yylt/agentsandbox/internal/pkg/api/pb;sandboxpbX\x04b\x06proto3"

var (
	file_sandbox_v1_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_v1_sandbox_proto_rawDescData []byte
)

func file_sandbox_v1_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)))
	})
	return file_sandbox_v1_sandbox_proto_rawDescData
}

var file_sandbox_v1_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_sandbox_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sandbox_v1_sandbox_proto_goTypes = []any{
	(ResourceKind)(0),               // 0: sandbox.v1.ResourceKind
	(ShutdownPolicy)(0),             // 1: sandbox.v1.ShutdownPolicy
	(NetworkPolicyManagement)(0),    // 2: sandbox.v1.NetworkPolicyManagement
	(EnvVarsInjectionPolicy)(0),     // 3: sandbox.v1.EnvVarsInjectionPolicy
	(WarmPoolUpdateStrategy)(0),     // 4: sandbox.v1.WarmPoolUpdateStrategy
	(*Metadata)(nil),                // 5: sandbox.v1.Metadata
	(*EnvVar)(nil),                  // 6: sandbox.v1.EnvVar
	(*ContainerPort)(nil),           // 7: sandbox.v1.ContainerPort
	(*Container)(nil),               // 8: sandbox.v1.Container
	(*PodTemplate)(nil),             // 9: sandbox.v1.PodTemplate
	(*SandboxResource)(nil),         // 10: sandbox.v1.SandboxResource
	(*SandboxTemplateResource)(nil), // 11: sandbox.v1.SandboxTemplateResource
	(*SandboxClaimResource)(nil),    // 12: sandbox.v1.SandboxClaimResource
	(*SandboxWarmPoolResource)(nil), // 13: sandbox.v1.SandboxWarmPoolResource
	(*ManagedResource)(nil),         // 14: sandbox.v1.ManagedResource
	(*CreateResourceRequest)(nil),   // 15: sandbox.v1.CreateResourceRequest
	(*GetResourceRequest)(nil),      // 16: sandbox.v1.GetResourceRequest
	(*ListResourcesRequest)(nil),    // 17: sandbox.v1.ListResourcesRequest
	(*UpdateResourceRequest)(nil),   // 18: sandbox.v1.UpdateResourceRequest
	(*DeleteResourceRequest)(nil),   // 19: sandbox.v1.DeleteResourceRequest
	(*ResourceResponse)(nil),        // 20: sandbox.v1.ResourceResponse
	(*ListResourcesResponse)(nil),   // 21: sandbox.v1.ListResourcesResponse
	nil,                             // 22: sandbox.v1.Metadata.LabelsEntry
	nil,                             // 23: sandbox.v1.Metadata.AnnotationsEntry
	nil,                             // 24: sandbox.v1.PodTemplate.LabelsEntry
	nil,                             // 25: sandbox.v1.PodTemplate.AnnotationsEntry
	(*emptypb.Empty)(nil),           // 26: google.protobuf.Empty
}
var file_sandbox_v1_sandbox_proto_depIdxs = []int32{
	22, // 0: sandbox.v1.Metadata.labels:type_name -> sandbox.v1.Metadata.LabelsEntry
	23, // 1: sandbox.v1.Metadata.annotations:type_name -> sandbox.v1.Metadata.AnnotationsEntry
	6,  // 2: sandbox.v1.Container.env:type_name -> sandbox.v1.EnvVar
	7,  // 3: sandbox.v1.Container.ports:type_name -> sandbox.v1.ContainerPort
	24, // 4: sandbox.v1.PodTemplate.labels:type_name -> sandbox.v1.PodTemplate.LabelsEntry
	25, // 5: sandbox.v1.PodTemplate.annotations:type_name -> sandbox.v1.PodTemplate.AnnotationsEntry
	8,  // 6: sandbox.v1.PodTemplate.containers:type_name -> sandbox.v1.Container
	5,  // 7: sandbox.v1.SandboxResource.metadata:type_name -> sandbox.v1.Metadata
	9,  // 8: sandbox.v1.SandboxResource.pod_template:type_name -> sandbox.v1.PodTemplate
	1,  // 9: sandbox.v1.SandboxResource.shutdown_policy:type_name -> sandbox.v1.ShutdownPolicy
	5,  // 10: sandbox.v1.SandboxTemplateResource.metadata:type_name -> sandbox.v1.Metadata
	9,  // 11: sandbox.v1.SandboxTemplateResource.pod_template:type_name -> sandbox.v1.PodTemplate
	2,  // 12: sandbox.v1.SandboxTemplateResource.network_policy_management:type_name -> sandbox.v1.NetworkPolicyManagement
	3,  // 13: sandbox.v1.SandboxTemplateResource.env_vars_injection_policy:type_name -> sandbox.v1.EnvVarsInjectionPolicy
	5,  // 14: sandbox.v1.SandboxClaimResource.metadata:type_name -> sandbox.v1.Metadata
	6,  // 15: sandbox.v1.SandboxClaimResource.env:type_name -> sandbox.v1.EnvVar
	1,  // 16: sandbox.v1.SandboxClaimResource.shutdown_policy:type_name -> sandbox.v1.ShutdownPolicy
	5,  // 17: sandbox.v1.SandboxWarmPoolResource.metadata:type_name -> sandbox.v1.Metadata
	4,  // 18: sandbox.v1.SandboxWarmPoolResource.update_strategy:type_name -> sandbox.v1.WarmPoolUpdateStrategy
	0,  // 19: sandbox.v1.ManagedResource.kind:type_name -> sandbox.v1.ResourceKind
	10, // 20: sandbox.v1.ManagedResource.sandbox:type_name -> sandbox.v1.SandboxResource
	11, // 21: sandbox.v1.ManagedResource.template:type_name -> sandbox.v1.SandboxTemplateResource
	12, // 22: sandbox.v1.ManagedResource.claim:type_name -> sandbox.v1.SandboxClaimResource
	13, // 23: sandbox.v1.ManagedResource.warm_pool:type_name -> sandbox.v1.SandboxWarmPoolResource
	14, // 24: sandbox.v1.CreateResourceRequest.resource:type_name -> sandbox.v1.ManagedResource
	0,  // 25: sandbox.v1.GetResourceRequest.kind:type_name -> sandbox.v1.ResourceKind
	0,  // 26: sandbox.v1.ListResourcesRequest.kind:type_name -> sandbox.v1.ResourceKind
	14, // 27: sandbox.v1.UpdateResourceRequest.resource:type_name -> sandbox.v1.ManagedResource
	0,  // 28: sandbox.v1.DeleteResourceRequest.kind:type_name -> sandbox.v1.ResourceKind
	14, // 29: sandbox.v1.ResourceResponse.resource:type_name -> sandbox.v1.ManagedResource
	14, // 30: sandbox.v1.ListResourcesResponse.resources:type_name -> sandbox.v1.ManagedResource
	15, // 31: sandbox.v1.SandboxService.CreateResource:input_type -> sandbox.v1.CreateResourceRequest
	16, // 32: sandbox.v1.SandboxService.GetResource:input_type -> sandbox.v1.GetResourceRequest
	17, // 33: sandbox.v1.SandboxService.ListResources:input_type -> sandbox.v1.ListResourcesRequest
	18, // 34: sandbox.v1.SandboxService.UpdateResource:input_type -> sandbox.v1.UpdateResourceRequest
	19, // 35: sandbox.v1.SandboxService.DeleteResource:input_type -> sandbox.v1.DeleteResourceRequest
	20, // 36: sandbox.v1.SandboxService.CreateResource:output_type -> sandbox.v1.ResourceResponse
	20, // 37: sandbox.v1.SandboxService.GetResource:output_type -> sandbox.v1.ResourceResponse
	21, // 38: sandbox.v1.SandboxService.ListResources:output_type -> sandbox.v1.ListResourcesResponse
	20, // 39: sandbox.v1.SandboxService.UpdateResource:output_type -> sandbox.v1.ResourceResponse
	26, // 40: sandbox.v1.SandboxService.DeleteResource:output_type -> google.protobuf.Empty
	36, // [36:41] is the sub-list for method output_type
	31, // [31:36] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_sandbox_v1_sandbox_proto_init() }
func file_sandbox_v1_sandbox_proto_init() {
	if File_sandbox_v1_sandbox_proto != nil {
		return
	}
	file_sandbox_v1_sandbox_proto_msgTypes[9].OneofWrappers = []any{
		(*ManagedResource_Sandbox)(nil),
		(*ManagedResource_Template)(nil),
		(*ManagedResource_Claim)(nil),
		(*ManagedResource_WarmPool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_v1_sandbox_proto_depIdxs,
		EnumInfos:         file_sandbox_v1_sandbox_proto_enumTypes,
		MessageInfos:      file_sandbox_v1_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_v1_sandbox_proto = out.File
	file_sandbox_v1_sandbox_proto_goTypes = nil
	file_sandbox_v1_sandbox_proto_depIdxs = nil
}
