apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-sandbox-system
resources:
- namespace.yaml
- crds/agents.x-k8s.io_sandboxes.yaml
- crds/extensions.agents.x-k8s.io_sandboxclaims.yaml
- crds/extensions.agents.x-k8s.io_sandboxtemplates.yaml
- crds/extensions.agents.x-k8s.io_sandboxwarmpools.yaml
- rbac.yaml
- configmap.yaml
- controller.yaml
- agent.yaml
- service.yaml
