apiVersion: v1
kind: Service
metadata:
  name: agent-sandbox-agent
  namespace: agent-sandbox-system
spec:
  selector:
    app.kubernetes.io/name: agent-sandbox-agent
  ports:
  - name: http
    port: 8080
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
spec:
  selector:
    app.kubernetes.io/name: agent-sandbox-controller
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  - name: http
    port: 8082
    targetPort: http
  - name: grpc
    port: 9090
    targetPort: grpc
